// Frases en español — autores hispanohablantes y frases que suenan naturales en español
const quotesEs = [
  { text: "El secreto para avanzar es empezar.", author: "Mark Twain" },
  { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
  { text: "Somos lo que hacemos repetidamente. La excelencia no es un acto, sino un hábito.", author: "Aristóteles" },
  { text: "Cae siete veces, levántate ocho.", author: "Proverbio japonés" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
  { text: "La disciplina es el puente entre metas y logros.", author: "Jim Rohn" },
  { text: "Lo que no te mata te hace más fuerte.", author: "Friedrich Nietzsche" },
  { text: "Si puedes soñarlo, puedes hacerlo.", author: "Walt Disney" },
  { text: "Haz algo hoy que tu yo del futuro te agradezca.", author: "Anónimo" },
  { text: "No busques el momento perfecto. Toma el momento y hazlo perfecto.", author: "Anónimo" },
  { text: "La constancia es la madre del dominio.", author: "Robin Sharma" },
  { text: "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.", author: "Proverbio chino" },
  { text: "Empieza donde estás. Usa lo que tienes. Haz lo que puedas.", author: "Arthur Ashe" },
  { text: "Sueña en grande. Empieza pequeño. Actúa ahora.", author: "Robin Sharma" },
  { text: "Tu futuro se crea por lo que haces hoy, no mañana.", author: "Robert Kiyosaki" },
  { text: "El dolor que sientes hoy será la fuerza que sentirás mañana.", author: "Anónimo" },
  { text: "No te detengas cuando estés cansado. Detente cuando hayas terminado.", author: "Anónimo" },
  { text: "El trabajo duro supera al talento cuando el talento no trabaja duro.", author: "Tim Notke" },
  { text: "La vida se encoge o se expande en proporción al coraje de uno.", author: "Anaïs Nin" },
  { text: "No te compares con los demás. Compárate con quien eras ayer.", author: "Jordan Peterson" },
  { text: "El éxito no es final, el fracaso no es fatal. Lo que cuenta es el coraje de continuar.", author: "Winston Churchill" },
  { text: "La única persona que puedes ser mejor es tú mismo.", author: "Anónimo" },
  { text: "Gana la mañana, gana el día.", author: "Tim Ferriss" },
  { text: "Una pequeña mejora diaria del 1% se acumula en resultados extraordinarios.", author: "James Clear" },
  { text: "Lo que se mide, mejora.", author: "Peter Drucker" },
  { text: "Motivación es lo que te pone en marcha. El hábito es lo que te mantiene.", author: "Jim Ryun" },
  { text: "No esperes la motivación. Actúa y la motivación llegará.", author: "Anónimo" },
  { text: "Cada día es una nueva oportunidad para cambiar tu vida.", author: "Anónimo" },
  { text: "Si siempre haces lo que siempre has hecho, siempre obtendrás lo que siempre has obtenido.", author: "Henry Ford" },
  { text: "La excelencia no es una habilidad, es una actitud.", author: "Ralph Marston" },
  { text: "Primero olvida la inspiración. El hábito es más confiable.", author: "Octavia Butler" },
  { text: "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.", author: "Zig Ziglar" },
  { text: "La autodisciplina es la magia detrás de cualquier logro.", author: "Dan Kennedy" },
  { text: "Tu cuerpo puede resistir casi cualquier cosa. Es tu mente la que debes convencer.", author: "Anónimo" },
  { text: "El único límite a nuestros logros de mañana son nuestras dudas de hoy.", author: "Franklin D. Roosevelt" },
  { text: "Construye buenos hábitos y deja que ellos te construyan a ti.", author: "Anónimo" },
  { text: "La persistencia puede cambiar el fracaso en un logro extraordinario.", author: "Matt Biondi" },
  { text: "Cada logro grande comienza con la decisión de intentarlo.", author: "Anónimo" },
  { text: "El progreso, no la perfección, es lo que debemos pedirle a la vida.", author: "Julia Cameron" },
  { text: "Nunca es tarde para ser lo que podrías haber sido.", author: "George Eliot" },
  { text: "La grandeza no viene de las circunstancias, viene de la elección consciente.", author: "Jim Collins" },
  { text: "El talento es común. La dedicación constante es rara.", author: "Anónimo" },
  { text: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
  { text: "Hacer las cosas a medias es agotador. Solo terminar lo que empiezas da energía.", author: "Anónimo" },
  { text: "No es la fuerza, sino la constancia de los grandes esfuerzos lo que produce la excelencia.", author: "Samuel Johnson" },
  { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
  { text: "La vida es lo que sucede mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
  { text: "En el medio de cada dificultad yace una oportunidad.", author: "Albert Einstein" },
  { text: "Primero forma tus hábitos, luego tus hábitos te forman a ti.", author: "John Dryden" },
  { text: "El camino de mil millas comienza con un solo paso.", author: "Lao Tse" },
  { text: "Lo que hagas hoy puede mejorar todos tus mañanas.", author: "Ralph Marston" },
  { text: "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre.", author: "Mahatma Gandhi" },
  { text: "La salud es la mayor posesión. La alegría es el mayor tesoro.", author: "Lao Tse" },
  { text: "Nadie puede volver atrás y empezar de nuevo, pero cualquiera puede empezar hoy.", author: "María Robinson" },
  { text: "Las personas que son lo suficientemente locas como para pensar que pueden cambiar el mundo son quienes lo hacen.", author: "Steve Jobs" },
  { text: "Un guerrero no se rinde cuando tiene hambre. La rendición es para la mente, no para el cuerpo.", author: "Carlos Castaneda" },
  { text: "El secreto de tu futuro está escondido en tu rutina diaria.", author: "Mike Murdock" },
  { text: "No importa lo lento que vayas, siempre y cuando no te detengas.", author: "Confucio" },
  { text: "Los límites existen solo en el alma de los que no sueñan.", author: "Herbert George Wells" },
  { text: "Convierte tus heridas en sabiduría.", author: "Oprah Winfrey" },
  { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
  { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi" },
  { text: "Vivir bien y de forma justa es la mejor venganza.", author: "Marco Aurelio" },
  { text: "Concentra todos tus pensamientos en la tarea que tienes entre manos.", author: "Alexander Graham Bell" },
  { text: "La acción es la clave fundamental de todo éxito.", author: "Pablo Picasso" },
  { text: "Esfuérzate no para tener éxito, sino para tener valor.", author: "Albert Einstein" },
  { text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", author: "Séneca" },
  { text: "No te des por vencido. El comienzo siempre es lo más difícil.", author: "Anónimo" },
  { text: "El que no arriesga nada, no gana nada.", author: "Anónimo" },
  { text: "Cuídate de los gastos pequeños; una pequeña vía de agua hundirá un gran barco.", author: "Benjamin Franklin" },
  { text: "La fortaleza no proviene de la capacidad física. Proviene de una voluntad indomable.", author: "Mahatma Gandhi" },
]

// Best motivational quotes in English — originals, not translations
const quotesEn = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "We are what we repeatedly do. Excellence is not an act, but a habit.", author: "Aristotle" },
  { text: "Fall seven times, stand up eight.", author: "Japanese proverb" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "A 1% improvement every day compounds into extraordinary results.", author: "James Clear" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
  { text: "Your body can withstand almost anything. It's your mind you have to convince.", author: "Anon" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Do something today that your future self will thank you for.", author: "Anon" },
  { text: "Win the morning, win the day.", author: "Tim Ferriss" },
  { text: "The only person you should try to be better than is who you were yesterday.", author: "Anon" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Anon" },
  { text: "Success is not final, failure is not fatal. It's the courage to continue that counts.", author: "Winston Churchill" },
  { text: "First forget inspiration. Habit is more dependable.", author: "Octavia Butler" },
  { text: "Excellence is not a skill. It's an attitude.", author: "Ralph Marston" },
  { text: "The secret to your future is hidden in your daily routine.", author: "Mike Murdock" },
  { text: "We don't rise to the level of our expectations, we fall to the level of our training.", author: "Archilochus" },
  { text: "Consistency is the mother of mastery.", author: "Robin Sharma" },
  { text: "Self-discipline is the magic power that makes you virtually unstoppable.", author: "Dan Kennedy" },
  { text: "What gets measured, gets improved.", author: "Peter Drucker" },
  { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Don't wait for motivation. Act and motivation will follow.", author: "Anon" },
  { text: "Be the hardest worker in the room.", author: "Dwayne Johnson" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "The path of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Build good habits and let them build you.", author: "Anon" },
  { text: "Never too late to be what you might have been.", author: "George Eliot" },
  { text: "Progress, not perfection, is what we should ask of ourselves.", author: "Julia Cameron" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese proverb" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "You will never always be motivated. You have to learn to be disciplined.", author: "Anon" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Talent is common. Relentless dedication is rare.", author: "Anon" },
  { text: "Every action you take is a vote for the person you want to become.", author: "James Clear" },
  { text: "Show up. Every. Single. Day.", author: "Anon" },
  { text: "Strength does not come from physical capacity. It comes from indomitable will.", author: "Mahatma Gandhi" },
  { text: "The successful warrior is the average man with laser-like focus.", author: "Bruce Lee" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
  { text: "Endure and persist; this pain will turn to good by and by.", author: "Ovid" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The secret of discipline is motivation.", author: "Jim Rohn" },
  { text: "Stop wishing. Start doing.", author: "Anon" },
  { text: "You are what you repeatedly do.", author: "Will Durant" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "Good things come to those who sweat.", author: "Anon" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The harder you work, the luckier you get.", author: "Gary Player" },
  { text: "Sweat is just fat crying.", author: "Anon" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Your only limit is your mind.", author: "Anon" },
  { text: "Suffer the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "The body achieves what the mind believes.", author: "Anon" },
  { text: "A little progress each day adds up to big results.", author: "Satya Nani" },
]

// Devuelve la frase del día — cambia cada día, consistente dentro del mismo día
export function getDailyQuote(lang = 'es') {
  const pool = lang === 'en' ? quotesEn : quotesEs
  const dayIndex = Math.floor(Date.now() / 86400000) % pool.length
  return pool[dayIndex]
}
